### ISSUE TITLE
problem with internal links

### ISSUE THREAD

**Issue by johnmathews** [mindcruzer/pelican-encrypt-content#9]
Hi,

Thanks for this plugin. I've found today that I cannot link to other pages on my blog properly if the link is behind the password. The html address isn't created and instead the path to the file remains.

-- John

**Comment by mindcruzer** [comment]
Could you post an example? Or maybe a screenshot?

**Comment by johnmathews** [comment]
Hello - same content and markdown on both pages

http://johnmathews.eu/pw_example.html
http://johnmathews.eu/plain_example.html

**Comment by mindcruzer** [comment]
Sorry I never got a chance to look at this. From what I can see, with internal links (ie. referencing source file instead of generated html file) encrypting the address is not possible because generation of the final url happens to late. There is no signal available that late in the content generation process. I think the only solution would be to link to the generated HTML file name.
